import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./component/header";
import Footer from "./component/footer";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const hideheaderfooter = false;

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        {/* Header */}
        {!hideheaderfooter && <Header />}

        {/* Page Content */}
        <main className="pt-24">
          {children}
        </main>

        {/* Footer (Bottom only) */}
        {!hideheaderfooter && <Footer />}

      </body>
    </html>
  );
}
